version: '3'
services:
  bff_gateway:
    container_name: bff_gateway
    build: bff_gateway/
    restart: on-failure
    networks:
      - dboaz_net
  ms_auction:
    container_name: ms_auction
    build: ms_auction/
    restart: no
    networks:
      - dboaz_net
  ms_auth:
    container_name: ms_auth
    build: ms_auth/
    restart: no
    networks:
      - dboaz_net
  ms_bid:
    container_name: ms_bid
    build: ms_bid/
    restart: no
    networks:
      - dboaz_net
  ms_comment_rating:
    container_name: ms_comment_rating
    build: ms_comment_rating/
    restart: no
    networks:
      - dboaz_net
  ms_logistic:
    container_name: ms_logistic
    build: ms_logistic/
    restart: no
    networks:
      - dboaz_net
  ms_messaging:
    container_name: ms_messaging
    build: ms_messaging/
    restart: no
    networks:
      - dboaz_net
  ms_notification:
    container_name: ms_notification
    build: ms_notification/
    restart: no
    networks:
      - dboaz_net
  ms_payment:
    container_name: ms_payment
    build: ms_payment/
    restart: no
    networks:
      - dboaz_net
  ms_product:
    container_name: ms_product
    build: ms_product/
    restart: no
    networks:
      - dboaz_net
  ms_profile:
    container_name: ms_profile
    build: ms_profile/
    restart: no
    networks:
      - dboaz_net
networks:
  dboaz_net:
    driver: bridge