microservice:
  ms_product:
    name: ms_product
    version: v1
    description: Stores information about the products being auctioned, including descriptions, images, and specific details
    routes:
      info:
        title: Info API
        version: 1.0.0
        description: This api provide custom server information
        contact:
          email: gustavo.boaz@hotmail.com

springdoc:
  swagger-ui:
    path: /docs/swagger
  api-docs:
    path: /docs/openapi
