microservice:
  ms_payment:
    name: ms_payment
    version: v1
    description: Handles transactions payments upon successful completion of an auction
    routes:
      info:
        title: Info API
        version: 1.0.0
        description: This api provide custom server information
        contact:
          email: gustavo.boaz@hotmail.com

springdoc:
  swagger-ui:
    path: /docs/swagger
  api-docs:
    path: /docs/openapi
