spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

microservice:
  ms_bid:
    name: ms_bid
    version: v1
    description: Manages bidding logic during auctions, including tracking user bids
    routes:
      info:
        title: Info API
        version: 1.0.0
        description: This api provide custom server information
        contact:
          email: gustavo.boaz@hotmail.com

springdoc:
  swagger-ui:
    path: /docs/swagger
  api-docs:
    path: /docs/openapi

credentials:
  username: dboaz
  password: dboaz
  authorities: app

jwt:
  private.key: classpath:private.key
  public.key: classpath:public.pub