microservice:
  ms_auth:
    name: ms_auth
    version: v1
    description: Responsible for user management, authentication and authorization
    routes:
      info:
        title: Info API
        version: 1.0.0
        description: This api provide custom server information
        contact:
          email: gustavo.boaz@hotmail.com

springdoc:
  swagger-ui:
    path: /docs/swagger
  api-docs:
    path: /docs/openapi
