microservice:
  ms_messaging:
    name: ms_messaging
    version: v1
    description: Provides messaging functionality for communication between users during auctions
    routes:
      info:
        title: Info API
        version: 1.0.0
        description: This api provide custom server information
        contact:
          email: gustavo.boaz@hotmail.com

springdoc:
  swagger-ui:
    path: /docs/swagger
  api-docs:
    path: /docs/openapi
