name: Build all modules Maven

on:
  push:
    branches:
      - main_spring
  pull_request:
    branches:
      - main_spring

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Maven 3.6.3
        run: sudo apt-get install -y maven

      - name: Build All Modules
        run: mvn clean package
