name: Pipeline dboaz

on:
  push:
    branches:
      - main_spring
  pull_request:
    branches:
      - main_spring

jobs:
  build_lib_common:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build lib_common module
        run: mvn -pl lib_common clean package

  build_base_core:
    runs-on: ubuntu-latest
    needs: build_lib_common
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install core project with Maven
        run: |
          mvn -B install -DskipTests --file pom.xml

      - name: Build base_core module
        run: mvn -pl base_core clean package

  build_bff_gateway:
    runs-on: ubuntu-latest
    needs: build_base_core
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install core project with Maven
        run: |
          mvn -B install -DskipTests --file pom.xml

      - name: Build bff_gateway module
        run: mvn -pl bff_gateway clean package

  build_microservices:
    runs-on: ubuntu-latest
    needs: build_base_core
    strategy:
      matrix:
        service:
          - ms_auction
          - ms_auth
          - ms_bid
          - ms_comment_rating
          - ms_logistic
          - ms_messaging
          - ms_notification
          - ms_payment
          - ms_product
          - ms_profile
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install core project with Maven
        run: |
          mvn -B install -DskipTests --file pom.xml

      - name: Build ${{ matrix.service }} module
        run: mvn -pl ${{ matrix.service }} clean package

  build_qa_acceptance:
    runs-on: ubuntu-latest
    needs: build_microservices
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install core project with Maven
        run: |
          mvn -B install -DskipTests --file pom.xml

      - name: Build qa_acceptance module
        run: mvn -pl qa_acceptance clean verify
